language: node_js
before_script:
  - npm install -g npm
script:
  - npm --version
  - npm test
node_js:
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
matrix:
  include:
    - node_js: 17
      env: NODE_OPTIONS=--openssl-legacy-provider
